language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - echo "skipping tests"
before_deploy:
  - yarn run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local_dir: build
  on:
    branch: main
